### ISSUE TITLE
Incorrect backend selection for non-standard targets

### ISSUE THREAD

**Issue by ryankurte** [dalek-cryptography/curve25519-dalek#515] opened 2023-03-16 22:14 UTC
hi folks,

we're compiling for a non-standard (ie. out-of-tree) target which means target detection doesn't work, and setting `'--cfg=curve25519_dalek_bits="32"'` per the docs (via the environment _or_ `.cargo/config`) does not have any effect, resulting in the error:
```
Error: Unknown Rust target platform.
Please set cfg(curve25519_dalek_bits) explicitly either as 32 or 64.
```

digging into the `build.rs` script it appears y'all are using `cfg` flags to switch features, however, when cross compiling these are not propagated to native components (ie. build scripts) at build time, only when they are executed (so in effect these are always ignored for foreign targets?).

via https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags:

> If the --target flag (or [build.target](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget)) is used, then the flags will only be passed to the compiler for the target. Things being built for the host, such as build scripts or proc macros, will not receive the args. Without --target, the flags will be passed to all compiler invocations (including build scripts and proc macros) because dependencies are shared. If you have args that you do not want to pass to build scripts or proc macros and are building for the host, pass --target with the host triple.

based on the intent here it appears this should instead be switching on environmental variables as these are passed when the build script is _executed_ during compilation for the foreign target, so to have this behave as documented the fix would be something like:

``` diff
diff --git a/build.rs b/build.rs
index a4c6b3e..f22df58 100644
--- a/build.rs
+++ b/build.rs
@@ -11,14 +11,17 @@ enum DalekBits {
 }

 fn main() {
-    #[cfg(curve25519_dalek_bits = "32")]
-    let curve25519_dalek_bits = DalekBits::Dalek32;
-
-    #[cfg(curve25519_dalek_bits = "64")]
-    let curve25519_dalek_bits = DalekBits::Dalek64;
-
-    #[cfg(all(not(curve25519_dalek_bits = "64"), not(curve25519_dalek_bits = "32")))]
-    let curve25519_dalek_bits = deterministic::determine_curve25519_dalek_bits();
+    let curve25519_dalek_bits = match std::env::var("CARGO_CFG_CURVE25519_DALEK_BITS").as_deref() {
+        Ok("32") => DalekBits::Dalek32,
+        Ok("64") => DalekBits::Dalek64,
+        _ => deterministic::determine_curve25519_dalek_bits(),
+    };

     match curve25519_dalek_bits {
         DalekBits::Dalek64 => println!("cargo:rustc-cfg=curve25519_dalek_bits=\"64\""),
```

happy to open a PR if y'all would be open to this fix?

**Comment by pinkforest** [comment] 2023-03-17 06:28
Not an issue in this crate - it has to be fixed in the custom build tooling that does not signal `cfg` correctly.

This is now 3rd duplicate PR/issue about this same issue:
- #511 

This all works fine in Rust compatible build tooling and / or otherwise known target triplets.

We do not assume anything as assuming would lead to incorrect behaviour if someone is signalling the enviornment variable where they assume that would work and which we instruct them to use.

The current behaviour as-is is the correct behaviour in case of where both the target and build tooling is custom and where it doesn't follow what rustc expects from build tooling.

Which build tooling is being used so I can chase them up to address the issue instead of breaking this crate for everyone ?

**Comment by pinkforest** [comment] 2023-03-17 06:40
I suspect you need to make `RUSTFLAGS` gets relayed to cargo in your Makefile here:
https://github.com/mobilecoinofficial/ledger-mob/blob/main/Makefile

I assume you are using Makefile ?

**Comment by jrose-signal** [comment] 2023-03-17 17:14
So there are two things happening here: @ryankurte is pointing out that build.rs will not see RUSTFLAGS when cross-compiling; this is **correct**. However, as @pinkforest notes, **this has not been a problem for known targets**, and that's because the cfg settings in RUSTFLAGS take priority over the ones from build.rs.\* (If curve25519-dalek's build.rs did anything with the cfg options other than pass them down to the compiler, this *would* be a problem even for built-in targets.)

So what *is* the problem? `Please set cfg(curve25519_dalek_bits) explicitly either as 32 or 64.` This cannot be detected from build.rs when cross-compiling; it has to be checked in the main source. Or checked via something other than `cfg`, as @ryankurte suggests.

\* [Here's a test case](https://github.com/dalek-cryptography/curve25519-dalek/files/11003976/test-build.zip); compare `RUSTFLAGS='--cfg foo="32"' cargo run` with `RUSTFLAGS='--cfg foo="32"' cargo run --target $YOUR_HOST_TRIPLE`.

**Comment by tarcieri** [comment] 2023-03-17 17:20
It seems like we've had enough issues around this we should just pick a default for unknown platforms (and possibly print a warning?)

**Comment by ryankurte** [comment] 2023-03-17 20:11
> as @pinkforest notes, this has not been a problem for known targets, and that's because the cfg settings in RUSTFLAGS take priority over the ones from build.rs.*

i am pretty sure this is actually because when cross compiling the flag is always ignored but [`deterministic::determine_curve25519_dalek_bits()`](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/build.rs#L21) works for targets that're built-in.

i have also confirmed that this occurs whether `RUSTFLAGS` are set via environmental variable or `.cargo/config.toml` (where `idk.json` is from `rustc +nightly -Z unstable-options --print target-spec-json --target thumbv7m-none-eabi`):
```
 RUSTFLAGS='--cfg curve25519_dalek_bits="32"' cargo build --target ./idk.json
   Compiling rustc-std-workspace-core v1.99.0 (/home/ryan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling curve25519-dalek v4.0.0-rc.1
error: failed to run custom build command for `curve25519-dalek v4.0.0-rc.1`

Caused by:
  process didn't exit successfully: `/home/ryan/projects/experiments/something/target/debug/build/curve25519-dalek-f762beaf00f2b7e7/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ryan/.cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-4.0.0-rc.1/build.rs:17:63
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

[dalek-repro.zip](https://github.com/dalek-cryptography/curve25519-dalek/files/11005450/dalek-repro.zip)

> It seems like we've had enough issues around this we should just pick a default for unknown platforms (and possibly print a warning?)

a default is a great idea! but even when you get a warning the current mechanisms for backend selection do not work as intended or documented which seems worth a fix?

via https://docs.rs/curve25519-dalek/4.0.0-rc.1/curve25519_dalek/index.html#word-size-for-serial-backends:
> Backend word size can be overridden for [default] and fiat by setting the environment variable:
> RUSTFLAGS='--cfg curve25519_dalek_bits="SIZE"'
> where SIZE is 32 or 64. As in the above section, this can also be placed in ~/.cargo/config.

**Comment by pinkforest** [comment] 2023-03-17 20:21
You are using Makefile - you need to put the environment variable there.

Please use existing issue:
- https://github.com/dalek-cryptography/curve25519-dalek/issues/511

**Comment by pinkforest** [comment] 2023-03-17 20:31
> where idk.json is from rustc +nightly -Z unstable-options --print target-spec-json --target thumbv7m-none-eabi

Try passing the --cfg here in idk.json

**Comment by pinkforest** [comment] 2023-03-17 20:33
This starts smelling like rustc bug.

**Comment by ryankurte** [comment] 2023-03-17 20:41
> I suspect this may be a cargo / rustc bug - I have a feeling it doesn't allow passing cfg with custom targets.

could very well be, there seem to be _a lot_ of assumptions around about custom targets and target naming ^_^

**Comment by pinkforest** [comment] 2023-03-17 20:42
Problem is if we now make default curve25519_dalek_bits default as 32 then people will have problems selecting backend.

Another way to address this could be to register these custom targets in platforms crate if they are widely used.

**Comment by pinkforest** [comment] 2023-03-17 20:45
What if we expose an environment variable for building for custom targets to set these ?

This would work/around the rustc issue not setting cfg correctly.

**Comment by ryankurte** [comment] 2023-03-17 20:46
> Then people also will have problems selecting backend so really need to get to bottom of this.

yeah my feeling exactly

> What if we expose an environment variable for building for custom targets to set these ?

i am not sure i understand the opposition to fixing the behaviour of build.rs, which makes the switching work as documented?

**Comment by pinkforest** [comment] 2023-03-17 21:04
I am trying to get to bottom of this since this also means people are not able to set these configuration settings.

It means nobody is being able to set backend either which is a big issue beyond this.

build.rs works fine otherwise - the issue is with cargo / rustc - we are effectively work/arounding over existing bug that.

**Comment by jrose-signal** [comment] 2023-03-17 21:06
This is *not the same issue* as #511. The problem here is that *using Cargo* and *using RUSTFLAGS* cross-compiling for an unsupported platform will fail, because build.rs has an explicit panic in it.

**Comment by pinkforest** [comment] 2023-03-17 21:12
It doesn't have that panic anymore - please use the main branch version.

For cross did you use the Cross.toml to passthrough RUSTFLAGS ?

We have two issues - environment issues where people don't passthrough RUSTFLAGS and custom targets.

**Comment by jrose-signal** [comment] 2023-03-17 21:13
> It doesn't have that panic anymore

@ryankurte Maybe that's enough to fix your issue? You're just using Cargo, right?

**Comment by pinkforest** [comment] 2023-03-17 21:15
> @ryankurte Maybe that's enough to fix your issue? You're just using Cargo, right?

This isn't since they are using custom target which involves a bug in rustc / cargo where rustc does not set cfg correctly.

**Comment by ryankurte** [comment] 2023-03-17 21:21
> It doesn't have that panic anymore - please use the main branch version.

no, this is still broken because of the `cfg` vs `env` problem, you just get the `Please set cfg(curve25519_dalek_bits) explicitly either as 32 or 64.` error instead.

> It means nobody is being able to set backend either which is a big issue beyond this.

yes, per my first post, manual backend selection for foreign targets is always ignored, which can be fixed by correctly using `env` instead of `cfg` in build.rs.

**Comment by pinkforest** [comment] 2023-03-17 21:22
Using environment variables is not a standard way to configure builds in Rust.

Standard way is to use cfg - there is nothing incorrect about it.

We will allow extra environment variables but cfg will take priority.

**Comment by ryankurte** [comment] 2023-03-17 21:25
> Standard way is to use cfg - there is nothing incorrect about it.

https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags
> If the --target flag (or [build.target](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget)) is used, then the flags will only be passed to the compiler for the target. Things being built for the host, such as build scripts or proc macros, will not receive the args

`cfg` is a build time selector, build.rs and proc macros are compiled -before- build and executed -at- build time, if you want build-time flags to be reflected in build.rs they need to be read at execution.

**Comment by pinkforest** [comment] 2023-03-17 21:26
Build target cfg flags are not the same as curve25519_dalek cfg flags we've specified.

**Comment by ryankurte** [comment] 2023-03-17 21:43
> cfg curve25519_dalek_bits and backend flags work correctly in standard targets with this build.rs just fine.

you can test this by patching out `determine_curve25519_dalek_bits` with a `panic` in build.rs

```diff
diff --git a/build.rs b/build.rs
index a4c6b3e..6944276 100644
--- a/build.rs
+++ b/build.rs
@@ -18,7 +18,7 @@ fn main() {
     let curve25519_dalek_bits = DalekBits::Dalek64;

     #[cfg(all(not(curve25519_dalek_bits = "64"), not(curve25519_dalek_bits = "32")))]
-    let curve25519_dalek_bits = deterministic::determine_curve25519_dalek_bits();
+    let curve25519_dalek_bits = panic!("whoops");

     match curve25519_dalek_bits {
         DalekBits::Dalek64 => println!("cargo:rustc-cfg=curve25519_dalek_bits=\"64\""),
```

if the overrides were working for foreign in-tree targets this should not be used or executed, and compilation with `RUSTFLAGS='--cfg curve25519_dalek_bits="32"' cargo build --target thumbv7m-none-eabi` should succeed, this is not the case.

**Comment by pinkforest** [comment] 2023-03-17 21:50
The overrides work with my cargo - by deriving Debug to DalekBits:

```rust
    #[cfg(curve25519_dalek_bits = "32")]
    let curve25519_dalek_bits = DalekBits::Dalek32;

    #[cfg(curve25519_dalek_bits = "64")]
    let curve25519_dalek_bits = DalekBits::Dalek64;

    panic!("{}", curve25519_dalek_bits);

```

$ env RUSTFLAGS='--cfg curve25519_dalek_bits="32"' cargo build
```
   Compiling curve25519-dalek v4.0.0-rc.1 (/home/foobar/cc/curve25519-dalek)

warning: `curve25519-dalek` (build script) generated 1 warning
error: failed to run custom build command for `curve25519-dalek v4.0.0-rc.1 (/home/foobar/cc/curve25519-dalek)`

Caused by:
  process didn't exit successfully: `/home/foobar/cc/curve25519-dalek/target/debug/build/curve25519-dalek-8f29bc9a97f12ab9/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Dalek32', build.rs:21:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#

```

Setting to 64 gives me Dalek64 as expected.

This is on otherwise 64bit target_pointer_width target.

What is the cargo / rustc version you are using ? I'm using various and the behaviour is same.

**Comment by ryankurte** [comment] 2023-03-17 21:54
> env RUSTFLAGS='--cfg curve25519_dalek_bits="32"' cargo build

unless you have an override in `.cargo/config.toml` you seem to be compiling natively there, where the behaviour only changes for foreign targets? try with `--target thumbv7m-none-eabi`

**Comment by pinkforest** [comment] 2023-03-17 21:56
$ env RUSTFLAGS='--cfg curve25519_dalek_bits="64"' cargo build --target wasm32-wasi
```
  --- stderr
  Dalek32
```

This is incorrect - I thought I had this tested with wasm32-u-u sigh.

**Comment by ryankurte** [comment] 2023-03-17 22:05
> Now let's see how we address this.

the fix i proposed in the first post works for in-tree and custom foreign targets

**Comment by pinkforest** [comment] 2023-03-17 22:07
Yeah we'll use environment variable if the cfg is not present but we'll use curve25519_dalek_ env outside cargo_cfg

Need to check if the backend via `curve25519_dalek_backend` behaves the same way without build script.

**Comment by pinkforest** [comment] 2023-03-17 22:10
Oh yeah we can use CARGO_CFG_ indeed :+1:

**Comment by pinkforest** [comment] 2023-03-17 22:25
Also just confirmed - We still need the #[cfg] for native compiling.

**Comment by pinkforest** [comment] 2023-03-17 22:43
@ryankurte See #516 - I've added you as Co-authored-by given your fix.

I wonder whether we should set curve25519_dalek_bits to 32 if we don't have that environment variable and print out a warning.

**Closed** 2023-03-18 08:34 UTC
