### ISSUE TITLE
EdwardsPoint::decompress accepts y higher than field modulo

### ISSUE THREAD

**Issue by paulmillr** [dalek-cryptography/curve25519-dalek#380] opened 2022-01-10 00:38 UTC
EdwardsPoint::decompress accepts y higher than field modulo

Which is invalid as per RFC8032 5.1.3.

```
   Decoding a point, given as a 32-octet string, is a little more
   complicated.

   1.  First, interpret the string as an integer in little-endian
       representation.  Bit 255 of this number is the least significant
       bit of the x-coordinate and denote this value x_0.  The
       y-coordinate is recovered simply by clearing this bit.  If the
       resulting value is >= p, decoding fails.
```

**Comment by AnomalRoil** [comment] 2022-01-10 13:42
RFC8032 is about EdDSA, while this repo is really "just" about Curve25519, so I'd argue that this is not an issue for curve25519, but rather for the ed25519 repo.

That being said, it seems that currently https://github.com/dalek-cryptography/ed25519-dalek is directly using the `decompress` function without doing that check [because](https://github.com/dalek-cryptography/ed25519-dalek/blob/925eb9ea56192053c9eb93b9d30d1b9419eee128/src/public.rs#L96-L98):

``` 
    /// The caller is responsible for ensuring that the bytes passed into this
    /// method actually represent a `curve25519_dalek::curve::CompressedEdwardsY`
    /// and that said compressed point is actually a point on the curve.
 ```

Also the struct `EdwardsPoint` is guaranteed to hold a valid point on the curve:
https://github.com/dalek-cryptography/curve25519-dalek/blob/967d8b6c0e67100401ad66125b7399ccf509ae22/src/edwards.rs#L199-L201

E.g. what if I consider the CompressedEdwardsY value `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f`, once decompressed it will give me a point that is equivalent to the point `0x1200000000000000000000000000000000000000000000000000000000000000`:

```
PublicKey(CompressedEdwardsY: [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 127]), 
EdwardsPoint{
	X: FieldElement51([1765291371327528, 828421974544742, 17095614122396, 1955301457663811, 970631510557499]),
	Y: FieldElement51([2251799813685247, 2251799813685247, 2251799813685247, 2251799813685247, 2251799813685247]),
	Z: FieldElement51([1, 0, 0, 0, 0]),
	T: FieldElement51([250047292302165, 1400796659693882, 307721054203134, 1418429032669878, 1708768494238261])
})

PublicKey(CompressedEdwardsY: [18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 
EdwardsPoint{
	X': FieldElement51([1765291371327528, 828421974544742, 17095614122396, 1955301457663811, 970631510557499]),
	Y': FieldElement51([18, 0, 0, 0, 0]),
	Z': FieldElement51([1, 0, 0, 0, 0]),
	T': FieldElement51([250047292302165, 1400796659693882, 307721054203134, 1418429032669878, 1708768494238261])
})
```

And both are equal once converted into affine coordinate, since (X/Z, Y/Z) is equal to (X'/Z', Y'/Z'). 
(See [here](https://github.com/dalek-cryptography/ed25519-dalek/issues/157#issuecomment-889982013) to see how you can manually check this.)

It's also worth noticing that the `compress` function will properly do the reduction, so it just means we are accepting keys that are not properly encoded as per the RFC, but we are not generating them. 

On my side I don't really see any issue with that as long as we are using valid points. It's just about its encoding in the end and whether we accept "non-canonical" encodings or not I guess.

**Comment by paulmillr** [comment] 2022-01-10 14:00
It's behavior that defies specification. If dalek wants to behave by its own, it's cool, but a note in documentation should be added.

**Comment by AnomalRoil** [comment] 2022-01-10 14:01
That's for ed25519-dalek, not for curve25519-dalek IMO.

**Comment by paulmillr** [comment] 2022-01-10 14:06
Right, I should have probably opened it in ed repository...

**Comment by burdges** [comment] 2022-01-11 20:10
Issues like this matter primarily for consensus protocols with implementations in other languages.  There are other reasons the ed25519-dalek is not ideal for consensus, so the best place maybe https://github.com/ZcashFoundation/ed25519-zebra

**Comment by dconnolly** [comment] 2022-02-10 23:47
> Issues like this matter primarily for consensus protocols with implementations in other languages. There are other reasons the ed25519-dalek is not ideal for consensus, so the best place maybe https://github.com/ZcashFoundation/ed25519-zebra It does not adhere to the standard or have equivalent libs in other languages, but at least it makes implementing everything you'd want in consensus possible.

There is also at least one implementation in [Go](https://github.com/hdevalence/ed25519consensus) that is compatible with the validation criteria implemented in [`ed25519-zebra`](https://github.com/ZcashFoundation/ed25519-zebra) and specified in [ZIP-215](https://zips.z.cash/zip-0215)

**Comment by kayabaNerve** [comment] 2022-04-18 20:06
I'd personally prefer dalek include a decompress_canonical function due to the application of this outside of just EdDSA, with the hopes it can be more performant than the current solution (reserializing entirely). Such a function would need to check for both lack of reduction and if the sign bit was set for 0.

**Comment by tarcieri** [comment] 2023-03-28 22:25
FWIW NIST defines public key validation criteria in [SP 800-186 Appendix D.1.3: Twisted Edwards Curves](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-186.pdf):

> ## D.1.3. Twisted Edwards Curves
> ### D.1.3.1. Partial Public Key Validation
> **Inputs:**
> 1. Edwards curve E<sub>a,d</sub> defined over the prime field GF(p)
> 2. Point Q
>
> **Output:** ACCEPT or REJECT Q as an affine point on E<sub>a,d</sub>.
>
> **Process:**
> 1. Verify that both x and y are integers in the interval [0, p−1]. Output REJECT if verification fails.
> 2. Let Q = (x, y). Verify that (x, y) is a point on E<sub>a,d</sub> by checking that (x, y) satisfies the defining equation ax<sup>2</sup> + y<sup>2</sup> = 1 + dx<sup>2</sup>y<sup>2</sup>, where computations are carried out in GF(p). Output REJECT if verification fails.
> 3. Otherwise, output ACCEPT.
>
> ## D.1.3.2. Full Public Key Validation
> **Inputs:**
> 1. Edwards curve E<sub>a,d</sub> defined over the prime field GF(p)
> 2. Point Q
>
> **Output:** ACCEPT or REJECT Q as a point on E<sub>a,d</sub> of order n.
>
> **Process:**
> 1. Perform partial public key validation on Q using the procedure of Appendix D.1.3.1. Output REJECT if this procedure outputs REJECT.
> 2. If Q = (0,1), output REJECT.
> 3. Verify that nQ = (0,1). Output REJECT if verification fails.
> 4. Otherwise, output ACCEPT.

**Comment by rozbb** [comment] 2023-03-29 01:24
Ugh yup I think this merits breaking change in ed-

**Comment by tarcieri** [comment] 2023-05-29 21:23
My latest recommendation for this issue would be to add `EdwardsPoint::decompress_nist` which applies the NIST validation criteria, i.e. rejects y-coordinates which overflow the modulus.

That's a purely additive change and not a blocker for a 4.0 release.

**Comment by paulmillr** [comment] 2023-05-29 21:27
yeah, sounds good.

what about naming? just nist? it's also rfc8032, innit?

**Comment by tarcieri** [comment] 2023-05-29 21:33
Yes, though I imagine people concerned with following particular validation rules are going to be more concerned with NIST than RFC8032

**Comment by kayabaNerve** [comment] 2023-05-30 21:35
I'm more concerned with it being strict, not any specific standards. That means not only would it reject anything exceeding the modulus, yet also the negative identity.

**Comment by tarcieri** [comment] 2023-05-30 21:38
We can call it "strict" but that's a little nonspecific, especially when NIST has a further set of "strict" verification criteria.

If someone has a better suggestion for a name which covers RFC8032 vs NIST point validation criteria (or can spot any discrepancies between the two) that'd be good to know.

**Comment by kayabaNerve** [comment] 2023-05-30 21:53
My highlight wasn't on the naming, yet on the note NIST may allow negative identity. If it does, I don't care to use a NIST-matching function, I care to use a strict function offering canonicity. In order to make me, personally, happy, there may be a need for a `decompress_canonical`, and then in order to make standards-people happy, there may be a need for a distinct `decompress_nist`. I'd have to review the standard to comment exactly, and even then, my preference may not be worthy of inclusion directly in dalek. It'd just be a pain to write additional canonicity checks if the newly proposed function does happen to be incomplete w.r.t. that design criteria (as it's technically intended for a distinct criteria),

**Comment by tarcieri** [comment] 2024-02-12 20:09
I'm going to close this issue in favor of #626 which is a new feature tracking issue for implementing NIST's validation criteria.

Notably `EdwardsPoint::decompress` accepting a y-coordinate higher than the field modulus is expected behavior under the ZIP-215 validation criteria which is the intended baseline criteria implemented by these crates, but we can add new APIs that support stricter validation criteria.

So closing this as "working as intended".

**Closed by tarcieri** 2024-02-12 20:09 UTC
